### ISSUE TITLE
New version (1.0.3) still doesn't work

### ISSUE THREAD

**Issue by bushrang3r** [SubhamTyagi/AppLock#17]
Just installed 1.0.3
1. set up applock to lock an app
2. Start said app
3. App starts without any lock

**Comment by paulle** [comment]
Same here.

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/AppLock/issues/20#issuecomment-470165482

**Comment by paulle** [comment]
v1.0.4 is working here.
android9, sony xperia xz2
