### ISSUE TITLE
App Crashes When you click on Settings after listing Apps

### ISSUE THREAD

**Issue by horpeyloaded** [SubhamTyagi/AppLock#18]
#### Expected behavior

I expect to be shown **Settings panel** without obstruction.  

#### Actual behavior

After the app has listed list of system apps and installed apps, click on **Settings** and the app crash with error "Unfortunately app has stopped"

#### How to reproduce

- Open app
- Input your pin or pattern
- Wait for secs for app to list system and installed apps, click on **Settings**.

***
* App version: v1.0.3
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

<img src="https://i.ibb.co/yns0PmC/G-20190304-0910582.gif" alt="G-20190304-0910582" border="0">

**Comment by SubhamTyagi** [comment]
is older version of app works?
