### ISSUE TITLE
New version (1.0.4) still doesn't work

### ISSUE THREAD

**Issue by bushrang3r** [SubhamTyagi/AppLock#20]
Just installed 1.0.4

1. Set up applock to lock an app
2. Start said app
3. App starts without any lock

Same as #17

**Comment by SubhamTyagi** [comment]
can you try [this apk file](http://s000.tinyupload.com/index.php?file_id=21002934406909765033) .This is debug apk file

**Comment by JonnyTech** [comment]
The above v1.0.5 debug apk is not working - "App Lock keeps stopping" message displays as soon as app is started.
