### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [SubhamTyagi/AppLock#42]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by SubhamTyagi** [comment]
@leela52452 see [here]( https://github.com/SubhamTyagi/AppLock/tree/master/fastlane/metadata/android/en-US/changelogs)

**Comment by leela52452** [comment]
@SubhamTyagi 

i am aware of it.
thank you
