### ISSUE TITLE
Don't lock AppLock itself!

### ISSUE THREAD

**Issue by slackhead** [SubhamTyagi/AppLock#6]
I locked AppLock itself and now it's impossible to open it.  As soon as you enter the pattern it closes immediately.

The only thing is to uninstall it and reinstall it.  Please hide App Lock itself from the list of apps

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/AppLock/blob/81a7ed623a47f8ce8f5c0fe183838235896c91f9/app/src/main/java/com/lzx/lock/services/LoadAppListService.java#L68
